### ISSUE TITLE
紧急联系

### ISSUE THREAD

**Issue by shengwenzheng** [wanglei-huohua/vision_mini_program#1]

**Comment by martor-sv** [comment]
你说吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: shengwenzheng ***@***.***&gt;
发送时间: 2022年7月4日 15:28
收件人: wanglei-huohua/vision_mini_program ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wanglei-huohua/vision_mini_program] 紧急联系 (Issue #1)





 
你好，请与我联系：13148385296，有急事，谢谢！

**Comment by shengwenzheng** [comment]
请把这个"https://github.com/wanglei-huohua/education-flutter"项目私有掉或者删掉，感激不尽。



在 2022-07-04 15:40:05，"王雷" ***@***.***> 写道：

你说吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: shengwenzheng ***@***.***&gt;
发送时间: 2022年7月4日 15:28
收件人: wanglei-huohua/vision_mini_program ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wanglei-huohua/vision_mini_program] 紧急联系 (Issue #1)






你好，请与我联系：13148385296，有急事，谢谢！
